# Array Creation: conversion from other python structures

In [2]:
import numpy as np

In [3]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
listarray.dtype

dtype('int32')

In [7]:
listarray.shape

(3, 3)

In [8]:
listarray.size

9

In [11]:
lspace = np.linspace(1,4,5)

In [12]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [13]:
rng=np.arange(32)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [15]:
arr = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
ar=np.array(arr)

In [17]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
ar.sum(axis=0)

array([12, 15, 18])

In [19]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [20]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
one=np.array([3,1,44,12])

In [22]:
one.argmax()

np.int32(2)

In [23]:
one.argmin()


np.int32(1)

In [24]:
one.argsort()

array([1, 0, 3, 2])

In [25]:
one.argmax()

np.int32(2)

In [26]:
one.argsort()

array([1, 0, 3, 2])

In [27]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [29]:
ar.argmax()


np.int32(8)